<a href="https://colab.research.google.com/github/Natbel-Ov/data_science/blob/main/13_numpy_sorting_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy Sorting Arrays

##Sorting Arrays
Sorting means putting elements in a ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

**Example**

Sort the array:

In [ ]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


> *Note: This method returns a copy of the array, leaving the original array unchanged.

You can also sort arrays of strings, or any other data type:

Example
Sort the array alphabetically:

> **Note:** This method returns a copy of the array, leaving the original array unchanged.

You can also sort arrays of strings, or any other data type:

**Example**

Sort the array alphabetically:

In [ ]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


**Example**

Sort a boolean array:

In [ ]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


##Sorting a 2-D Array
If you use the sort() method on a 2-D array, both arrays will be sorted:

**Example**

Sort a 2-D array:

In [ ]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
